<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => '1',
                'username' => 'root',
                'first_name' => 'Ali',
                'last_name' => 'Noual',
                'email' => 'noualdev@gmail.com',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$PbtJsEebDnXgN6J4M7OJ1.CrANtuealKrGa380AwrMS4Fp.ML.paq',
                'remember_token' => NULL,
                'created_at' => '2022-12-11 21:55:55.0000000',
                'updated_at' => '2023-04-11 22:18:05.1360000',
                'must_change_password' => '0',
            ),
            1 => 
            array (
                'id' => '2',
                'username' => 'DCP',
                'first_name' => 'Chiraz',
                'last_name' => 'Bechiri',
                'email' => 'DCPermanant@bna.dz',
                'phone' => NULL,
                'avatar' => '/images/avatars/dcp.png',
                'password' => '$2y$10$3/YP9h30I5oGhES.7YsvCeUC7l3pvHkzBB34gncwWy4pJwomnPJUy',
                'remember_token' => NULL,
                'created_at' => '2022-12-11 21:55:56.0000000',
                'updated_at' => '2023-04-16 14:26:33.4360000',
                'must_change_password' => '0',
            ),
            2 => 
            array (
                'id' => '3',
                'username' => 'CDRCP',
                'first_name' => 'Fazia',
                'last_name' => 'Nait Slimane',
                'email' => 'DRCP@bna.dz',
                'phone' => NULL,
                'avatar' => '/images/avatars/drcp.png',
                'password' => '$2y$10$XlA2e5zgUQpDAsRw8VSNX.d7eRQfNWEwt86aBLencrgmxlUzBQlya',
                'remember_token' => NULL,
                'created_at' => '2022-12-11 21:55:56.0000000',
                'updated_at' => '2023-05-27 21:59:35.8020000',
                'must_change_password' => '0',
            ),
            3 => 
            array (
                'id' => '4',
                'username' => 'DG',
                'first_name' => 'Mohammed Lamine',
                'last_name' => 'Lebbou',
                'email' => 'dg@bna.dz',
                'phone' => NULL,
                'avatar' => '/images/avatars/dg.png',
                'password' => '$2y$10$Ri1HiO3514.T0zUsReLM3.kcd56BfAa8d.voIKjzvshDMdIosqaYe',
                'remember_token' => NULL,
                'created_at' => '2022-12-11 21:55:56.0000000',
                'updated_at' => '2023-04-19 11:30:49.6360000',
                'must_change_password' => '0',
            ),
            4 => 
            array (
                'id' => '17',
                'username' => 'z.benmadi',
                'first_name' => 'Zakarya',
                'last_name' => 'Benmadi',
                'email' => 'z.benmadi@gmail.com',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$qk.KV7h9QUz2amQwINC8COwih94uTHoZAOmDD5JaQwgAsWXtPzd2e',
                'remember_token' => NULL,
                'created_at' => '2023-01-20 12:20:45.0000000',
                'updated_at' => '2023-04-11 21:51:58.6780000',
                'must_change_password' => '0',
            ),
            5 => 
            array (
                'id' => '19',
                'username' => 'm.touahri',
                'first_name' => 'Mohamed',
                'last_name' => 'Touahri',
                'email' => 'moh.touahri@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$uDCEBZsvfdYOMb7J0gY1kej5ndbFtyOnjZT3UbFNgdQ7GpTo3C8FO',
                'remember_token' => NULL,
                'created_at' => '2023-02-14 17:41:07.0000000',
                'updated_at' => '2023-05-26 17:29:00.8360000',
                'must_change_password' => '0',
            ),
            6 => 
            array (
                'id' => '20',
                'username' => 'IG',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'ig@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$7qZ6K4vKcWOb3HEnfdQwpuywthKjY9eFg/bPNQ92J2dyZ3UBVDIe.',
                'remember_token' => NULL,
                'created_at' => '2023-02-17 23:51:49.0000000',
                'updated_at' => '2023-02-18 13:40:16.0000000',
                'must_change_password' => '0',
            ),
            7 => 
            array (
                'id' => '23',
                'username' => 'm.mustapha',
                'first_name' => 'Mustapha',
                'last_name' => 'Mendil',
                'email' => 'mumuste.mend@gmail.com',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$jfcjYfSXNI6CgQFg6YSVWujNVfRFKDRV4m/b0OkZn1iPh0qzgBHbG',
                'remember_token' => NULL,
                'created_at' => '2023-02-19 20:53:19.0000000',
                'updated_at' => '2023-02-19 20:53:19.0000000',
                'must_change_password' => '0',
            ),
            8 => 
            array (
                'id' => '25',
                'username' => 'DER',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'der@gmail.com',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$9DrMeUp4pZKR9Yd3pdKaWOH7WnHgo5dW53HNpOW7gz98t9gNZyktC',
                'remember_token' => NULL,
                'created_at' => '2023-02-23 10:58:19.0000000',
                'updated_at' => '2023-05-27 19:36:34.4300000',
                'must_change_password' => '0',
            ),
            9 => 
            array (
                'id' => '26',
                'username' => 'h.belloundja',
                'first_name' => 'Hassiba',
                'last_name' => 'Belloundja',
                'email' => 'h.belloundja@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$ye6y9bodu0ejV00lH3XXC.82vvRjbzDbWBILHhGZlrFs3r9pbvada',
                'remember_token' => NULL,
                'created_at' => '2023-03-29 14:15:19.0000000',
                'updated_at' => '2023-05-28 09:05:56.2400000',
                'must_change_password' => '0',
            ),
            10 => 
            array (
                'id' => '27',
                'username' => 'a.adjaoud',
                'first_name' => 'Abdelhadi',
                'last_name' => 'Adjaoud',
                'email' => 'a.adjaoud@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$xOEQtZ6YIVmh565E7TQqwOgs0CrcDw.ln8qqIVrUw6jzB4Jf9JKOu',
                'remember_token' => NULL,
                'created_at' => '2023-03-29 14:16:09.0000000',
                'updated_at' => '2023-04-12 07:29:49.0230000',
                'must_change_password' => '0',
            ),
            11 => 
            array (
                'id' => '38',
                'username' => '747',
                'first_name' => 'Malika',
                'last_name' => 'Maldji',
                'email' => 'DRE187controle@bna.dz',
                'phone' => '0540602924',
                'avatar' => NULL,
                'password' => '$2y$10$n7UYf.0YzoWL.l.iq5SZGuyfgoXoIuZSj0Kh51PMMiHuaU3ML8LLO',
                'remember_token' => NULL,
                'created_at' => '2023-04-12 02:39:34.6250000',
                'updated_at' => '2023-04-12 09:09:17.2020000',
                'must_change_password' => '0',
            ),
            12 => 
            array (
                'id' => '39',
                'username' => '6969',
                'first_name' => 'Djellali',
                'last_name' => 'Siham',
                'email' => 's.djellali@bna.dz',
                'phone' => '0555531013',
                'avatar' => NULL,
                'password' => '$2y$10$npj07Hc.dDGCuUKqaJKJ1uo1jEPhdI.ildv.Y8saOsLhGYQQ7j8ym',
                'remember_token' => NULL,
                'created_at' => '2023-04-12 02:40:57.7820000',
                'updated_at' => '2023-04-12 11:32:40.0040000',
                'must_change_password' => '0',
            ),
            13 => 
            array (
                'id' => '40',
                'username' => '362',
                'first_name' => 'Soumia',
                'last_name' => 'Merghit',
                'email' => 's.merghit@bna.dz',
                'phone' => '0696641162',
                'avatar' => NULL,
                'password' => '$2y$10$rbnm2CFxYJfFJqHOsUOzhOeJHtpfdjvZfo5keS7vbdeb9/f5wJuiy',
                'remember_token' => NULL,
                'created_at' => '2023-04-12 07:17:32.2270000',
                'updated_at' => '2023-04-17 09:46:44.7790000',
                'must_change_password' => '0',
            ),
            14 => 
            array (
                'id' => '41',
                'username' => '13057',
                'first_name' => 'Farid',
                'last_name' => 'Kheyar',
                'email' => 'f.kheyar@bna.dz',
                'phone' => '0550261370',
                'avatar' => NULL,
                'password' => '$2y$10$WTIWBPb.MiXaOVkdrH/nV.AuzAdvUaiNoAXschVM5Ziaiu0EEms6y',
                'remember_token' => NULL,
                'created_at' => '2023-04-12 07:18:22.9330000',
                'updated_at' => '2023-04-17 09:46:16.1000000',
                'must_change_password' => '0',
            ),
            15 => 
            array (
                'id' => '44',
                'username' => 'cdc-garidi',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'cdc-garidi@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$fPl91CAXEiHKsQ2yqLBOr.HqfsduZOGbcT0Bd9U090nE3TuvwJq/m',
                'remember_token' => NULL,
                'created_at' => '2023-05-13 14:12:16.0660000',
                'updated_at' => '2023-05-13 14:25:52.6890000',
                'must_change_password' => '0',
            ),
            16 => 
            array (
                'id' => '45',
                'username' => 'ci-garidi',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'ci-garidi@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$ft64i5vH4/O6tYWLIX5ql.9zgifw..ter4oTDP/h3l1.rpczTlHgC',
                'remember_token' => NULL,
                'created_at' => '2023-05-13 14:12:42.7990000',
                'updated_at' => '2023-05-13 14:51:00.8030000',
                'must_change_password' => '0',
            ),
            17 => 
            array (
                'id' => '46',
                'username' => 'da-633',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'da-633@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$Tp8GhYS6VEeQiES9Ba7BK.JLYMd5lb0v0kYOQJaYU/xdRHijlE/v.',
                'remember_token' => NULL,
                'created_at' => '2023-05-13 14:25:08.6390000',
                'updated_at' => '2023-05-13 14:25:08.6390000',
                'must_change_password' => '0',
            ),
            18 => 
            array (
                'id' => '47',
                'username' => 'cdcr',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'cdcr@dev.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$ZnRklmOYXC1jUAGwL6GWRuP2VlSFMt7dO2vRbb3Po3tBv104gT7yG',
                'remember_token' => NULL,
                'created_at' => '2023-05-16 17:59:07.8750000',
                'updated_at' => '2023-05-16 18:51:52.6690000',
                'must_change_password' => '0',
            ),
            19 => 
            array (
                'id' => '48',
                'username' => 'dre-garidi',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'dre-garidi@dev.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$I4ZKiOqpVG8cUy8cyWPIiunIJBk5Qo2cWzaYz8yrFgCLKSkciviDG',
                'remember_token' => NULL,
                'created_at' => '2023-05-16 19:03:32.9000000',
                'updated_at' => '2023-05-27 21:45:26.9710000',
                'must_change_password' => '0',
            ),
            20 => 
            array (
                'id' => '49',
                'username' => 'dre-bouzareah',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'dre-bouzareah@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$UIIeoa2ZS7wE90OhONLXw.dPTIT5InfPKO/SVUap83f3hdgDLXDNy',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 19:57:56.6840000',
                'updated_at' => '2023-05-27 19:57:56.6840000',
                'must_change_password' => '0',
            ),
            21 => 
            array (
                'id' => '50',
                'username' => 'DRE-EL-BIAR',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'DRE-EL-BIAR@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$Di5m8fcm1L25FUfyNoXbA.b9Z9nuyGNPhlP2FoXhffpFyqurndr6e',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 19:58:37.6890000',
                'updated_at' => '2023-05-27 19:58:37.6890000',
                'must_change_password' => '0',
            ),
            22 => 
            array (
                'id' => '51',
                'username' => 'DRE-KOLEA',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'DRE-KOLEA@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$b66J6JOAfOI94YNNGwAsEunyJ0tm69UDiEklcu5ARBWcCHa6NjGC.',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 20:01:54.3020000',
                'updated_at' => '2023-05-27 20:01:54.3020000',
                'must_change_password' => '0',
            ),
            23 => 
            array (
                'id' => '52',
                'username' => 'CDC-BOUZAREAH',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'CDC-BOUZAREAH@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$zdrVG9KnVeKNMFCQW1R6VOSPXyuT2npcS8ezXM1ee0ahLdPY42ima',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 20:42:17.4490000',
                'updated_at' => '2023-05-27 20:42:17.4490000',
                'must_change_password' => '0',
            ),
            24 => 
            array (
                'id' => '53',
                'username' => 'CDC-EL-BIAR',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'CDC-EL-BIAR@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$6RYCt.bEJJD5rIKHBHxm9uRAatkgAPc62P43yf0RZInZKMTpn9cI.',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 20:43:53.3570000',
                'updated_at' => '2023-05-27 20:43:53.3570000',
                'must_change_password' => '0',
            ),
            25 => 
            array (
                'id' => '54',
                'username' => 'CDC-KOLEA',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'CDC-KOLEA@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$uOlHN3LEad0tDC4qtYrNwO7VwI0zPPKlUUx877rwwPNCXXz5t6jM.',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 20:44:33.0430000',
                'updated_at' => '2023-05-27 20:44:33.0430000',
                'must_change_password' => '0',
            ),
            26 => 
            array (
                'id' => '55',
                'username' => 'CI-BOUZAREAH',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'CI-BOUZAREAH@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$W1gQI.VcLBxbziR2QH7Ruufz.a/OWOMASbIByIjXmw/IbuNtI75iK',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 20:46:09.0820000',
                'updated_at' => '2023-05-27 20:46:09.0820000',
                'must_change_password' => '0',
            ),
            27 => 
            array (
                'id' => '56',
                'username' => 'CI-EL-BIAR',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'CI-EL-BIAR@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$zZmDSGJ3IyHFq4KEzncKG.fDuxe46aYKh3Z9Y6eqHdaFm7.ukqt9K',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 20:46:48.6880000',
                'updated_at' => '2023-05-27 20:46:48.6880000',
                'must_change_password' => '0',
            ),
            28 => 
            array (
                'id' => '57',
                'username' => 'CI-KOLEA',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'CI-KOLEA@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$rP/0q9vQRAHiA5RUbSs/m.EbHZM4e7eFea6KTvDlwoeD2.egknsAO',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 20:47:18.9540000',
                'updated_at' => '2023-05-27 20:47:18.9540000',
                'must_change_password' => '0',
            ),
            29 => 
            array (
                'id' => '58',
                'username' => 'da-614',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'da-614@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$XJ6Vg9yfzM8B1csICbXqL.XCZUb7zDptQkKxrM4xbcZAj1GplgVlq',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 21:23:07.8140000',
                'updated_at' => '2023-05-27 21:23:07.8140000',
                'must_change_password' => '0',
            ),
            30 => 
            array (
                'id' => '59',
                'username' => 'da-617',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'da-617@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$qkcV79sEJPHIFDX/drsQ5uW72AXdm4FY9dScU5n01R1K8ZDyGXEhq',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 21:23:36.1110000',
                'updated_at' => '2023-05-27 21:23:36.1110000',
                'must_change_password' => '0',
            ),
            31 => 
            array (
                'id' => '60',
                'username' => 'da-622',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'da-622@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$MIe64ArVIgaJ9VFtZ2375eRStSnPwVOgXfVe8d2PO9gk0OLJxuhRC',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 21:24:10.7540000',
                'updated_at' => '2023-05-27 21:24:10.7540000',
                'must_change_password' => '0',
            ),
            32 => 
            array (
                'id' => '61',
                'username' => 'da-610',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'da-610@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$p9Ai/vQuePggxs/Uw9Mw.erpOHqdlFzoFOpeoeJUfHITGBA0a2GSO',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 21:24:35.7220000',
                'updated_at' => '2023-05-27 21:24:35.7220000',
                'must_change_password' => '0',
            ),
            33 => 
            array (
                'id' => '62',
                'username' => 'da-607',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'da-607@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$Fig1TTnJ4/bTEJVeipmLPOc3SDWpMOckPf5VvYSJLbX8MIMcRiimW',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 21:25:07.2580000',
                'updated_at' => '2023-05-27 21:25:07.2580000',
                'must_change_password' => '0',
            ),
            34 => 
            array (
                'id' => '63',
                'username' => 'da-615',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'da-615@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$0i1ZcmXvJQWL/jxeqgQuQ.jxFzj5/jnwlvvQUVCs/6Nu7RNxmUcXe',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 21:25:31.3250000',
                'updated_at' => '2023-05-27 21:25:31.3250000',
                'must_change_password' => '0',
            ),
            35 => 
            array (
                'id' => '64',
                'username' => 'da-605',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'da-605@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$H2V315Ro9Kg49GPpJY5ws.UVNXTNCi/QDTbLjCi4miv1rTGsd.Aky',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 21:26:15.4710000',
                'updated_at' => '2023-05-27 21:26:15.4710000',
                'must_change_password' => '0',
            ),
            36 => 
            array (
                'id' => '65',
                'username' => 'da-628',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'da-628@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$uf9M2eD2DGP9zDtIXX0YoOJ.xrRmU2GjTsuiOOfy4EgL.J8TOnRHe',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 21:26:39.3430000',
                'updated_at' => '2023-05-27 21:26:39.3430000',
                'must_change_password' => '0',
            ),
            37 => 
            array (
                'id' => '66',
                'username' => 'da-629',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'da-629@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$0410TwTY4bT7DmNfbgPFk.ugBGy8eLvOOztAu1QZ1BztQdPf0OvLi',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 21:27:29.1420000',
                'updated_at' => '2023-05-27 21:27:29.1420000',
                'must_change_password' => '0',
            ),
            38 => 
            array (
                'id' => '67',
                'username' => 'SG',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'SG@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$QY6Pg1Xr0nwsYxTnambGYOtNptR0g6Uw4qEOXJ/XchXzl06XXfKC2',
                'remember_token' => NULL,
                'created_at' => '2023-05-27 21:48:44.9960000',
                'updated_at' => '2023-05-27 21:48:44.9960000',
                'must_change_password' => '0',
            ),
            39 => 
            array (
                'id' => '68',
                'username' => 'dre-annaba',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'dre-annaba@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$DQPCRDJ082em8pTOSl00KeILTVGBN9.h0jgW2HLzBpOOeuuB7RMBe',
                'remember_token' => NULL,
                'created_at' => '2023-06-01 11:14:05.3310000',
                'updated_at' => '2023-06-01 11:14:05.3310000',
                'must_change_password' => '0',
            ),
            40 => 
            array (
                'id' => '69',
                'username' => 'da-810',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'da-810@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$22vIv6A4.M7jy//srtHtq.o35bYiMbT5Guc4G6RqZ9frCTqKHxPbW',
                'remember_token' => NULL,
                'created_at' => '2023-06-01 11:14:41.7270000',
                'updated_at' => '2023-06-01 11:14:41.7270000',
                'must_change_password' => '0',
            ),
            41 => 
            array (
                'id' => '70',
                'username' => 'cdc-annaba',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'cdc-annaba@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$8F9lPmyngfGAmQsOmOzUaOHT3tUvdc00Veo6yjiHz7ipyfeXGkgGW',
                'remember_token' => NULL,
                'created_at' => '2023-06-01 11:15:16.3820000',
                'updated_at' => '2023-06-01 11:15:16.3820000',
                'must_change_password' => '0',
            ),
            42 => 
            array (
                'id' => '71',
                'username' => 'ci-annaba',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'ci-annaba@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$btxN0/59xjkr1a7pLrjgcuUgep6bVClP/Q6X6qYxA16y4HUlpYUv2',
                'remember_token' => NULL,
                'created_at' => '2023-06-01 11:15:43.1440000',
                'updated_at' => '2023-06-01 11:15:43.1440000',
                'must_change_password' => '0',
            ),
            43 => 
            array (
                'id' => '72',
                'username' => 'dre-constantine',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'dre-constantine@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$3uSBhN8scLQYmAvlg2IxYOQoX4wgiiV.L5UmBxdIWZXzOiPnDTC8O',
                'remember_token' => NULL,
                'created_at' => '2023-06-03 23:34:43.9400000',
                'updated_at' => '2023-06-03 23:34:43.9400000',
                'must_change_password' => '0',
            ),
            44 => 
            array (
                'id' => '73',
                'username' => 'da-845',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'da-845@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$XoMTB268SMZaTxvRLAae5.Bt63KOvqmxChxnATfsAUJEpxvaJH1ou',
                'remember_token' => NULL,
                'created_at' => '2023-06-03 23:35:13.3940000',
                'updated_at' => '2023-06-03 23:35:13.3940000',
                'must_change_password' => '0',
            ),
            45 => 
            array (
                'id' => '74',
                'username' => 'cdc-constantine',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'cdc-constantine@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$8hYyutjN/d.nuAogWksy6uxa6iOpB7jwyEvAwV1bKshcka7hMrMay',
                'remember_token' => NULL,
                'created_at' => '2023-06-03 23:35:44.1900000',
                'updated_at' => '2023-06-03 23:35:44.1900000',
                'must_change_password' => '0',
            ),
            46 => 
            array (
                'id' => '75',
                'username' => 'ci-constantine',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'ci-constantine@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$xJTxPsnh7vID.h6GIU5a2uNXfdXYerPq26FpDtQgrfm4Mph4L74UW',
                'remember_token' => NULL,
                'created_at' => '2023-06-03 23:36:09.0250000',
                'updated_at' => '2023-06-03 23:36:09.0250000',
                'must_change_password' => '0',
            ),
            47 => 
            array (
                'id' => '76',
                'username' => 'dre-setif',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'dre-setif@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$5WEBEf3Vjmn80J8EJRGMA.t6B.XaFV.EK9z1mYn0NWqxr4w3EPBbC',
                'remember_token' => NULL,
                'created_at' => '2023-06-04 09:00:47.9050000',
                'updated_at' => '2023-06-04 09:00:47.9050000',
                'must_change_password' => '0',
            ),
            48 => 
            array (
                'id' => '77',
                'username' => 'cdc-setif',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'cdc-setif@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$pMBKERYjyNAPOcZLEtf8zeSxPnJ7sIK469rVFDh5LWf5mgcneKhS.',
                'remember_token' => NULL,
                'created_at' => '2023-06-04 09:01:11.4340000',
                'updated_at' => '2023-06-04 09:01:11.4340000',
                'must_change_password' => '0',
            ),
            49 => 
            array (
                'id' => '78',
                'username' => 'ci-setif',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'ci-setif@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$reRVZQpVC4xqmBQImOWzMuRbUphVjMbZjMitV5NizKvjdIyGXrCVy',
                'remember_token' => NULL,
                'created_at' => '2023-06-04 09:01:32.1510000',
                'updated_at' => '2023-06-04 09:01:32.1510000',
                'must_change_password' => '0',
            ),
            50 => 
            array (
                'id' => '79',
                'username' => 'da-704',
                'first_name' => NULL,
                'last_name' => NULL,
                'email' => 'da-704@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$kVNzBYX0LICNdSYIq1oySOFuS2iPVaWyuzjxz/gS2WwBtABksa/vm',
                'remember_token' => NULL,
                'created_at' => '2023-06-04 09:02:24.7200000',
                'updated_at' => '2023-06-04 09:02:24.7200000',
                'must_change_password' => '0',
            ),
            51 => 
            array (
                'id' => '80',
                'username' => 'd.kaci',
                'first_name' => 'Djazia',
                'last_name' => 'Kaci',
                'email' => 'd.kaci@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$U9Xt6iawqWzAHUZeaHEHieUSCWfkRv17NP9CautcJvbLa3EKnPZT2',
                'remember_token' => NULL,
                'created_at' => '2023-06-20 11:54:07.2280000',
                'updated_at' => '2023-06-20 11:54:07.2280000',
                'must_change_password' => '1',
            ),
            52 => 
            array (
                'id' => '81',
                'username' => 'h.rais',
                'first_name' => 'Hassiba',
                'last_name' => 'Rais',
                'email' => 'h.rais@bna.dz',
                'phone' => NULL,
                'avatar' => NULL,
                'password' => '$2y$10$v52ye/nulWdOwqM5JrJIOeSjqDegRdbUU469d1L.G7QsS3Wcz/vDm',
                'remember_token' => NULL,
                'created_at' => '2023-06-20 11:54:36.0310000',
                'updated_at' => '2023-06-20 11:54:36.0310000',
                'must_change_password' => '1',
            ),
        ));
        
        
    }
}