<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'avatar' => NULL,
                'created_at' => '2022-12-11 21:55:55',
                'email' => 'noualdev@gmail.com',
                'first_name' => 'Ali',
                'id' => 1,
                'last_name' => 'Noual',
                'must_change_password' => 0,
                'password' => '$2y$10$PbtJsEebDnXgN6J4M7OJ1.CrANtuealKrGa380AwrMS4Fp.ML.paq',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-04-11 22:18:05',
                'username' => 'root',
            ),
            1 => 
            array (
                'avatar' => '/images/avatars/dcp.png',
                'created_at' => '2022-12-11 21:55:56',
                'email' => 'DCPermanant@bna.dz',
                'first_name' => 'Chiraz',
                'id' => 2,
                'last_name' => 'Bechiri',
                'must_change_password' => 0,
                'password' => '$2y$10$3/YP9h30I5oGhES.7YsvCeUC7l3pvHkzBB34gncwWy4pJwomnPJUy',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-04-16 14:26:33',
                'username' => 'DCP',
            ),
            2 => 
            array (
                'avatar' => '/images/avatars/drcp.png',
                'created_at' => '2022-12-11 21:55:56',
                'email' => 'DRCP@bna.dz',
                'first_name' => 'Fazia',
                'id' => 3,
                'last_name' => 'Nait Slimane',
                'must_change_password' => 0,
                'password' => '$2y$10$XlA2e5zgUQpDAsRw8VSNX.d7eRQfNWEwt86aBLencrgmxlUzBQlya',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 21:59:36',
                'username' => 'CDRCP',
            ),
            3 => 
            array (
                'avatar' => '/images/avatars/dg.png',
                'created_at' => '2022-12-11 21:55:56',
                'email' => 'dg@bna.dz',
                'first_name' => 'Mohammed Lamine',
                'id' => 4,
                'last_name' => 'Lebbou',
                'must_change_password' => 0,
                'password' => '$2y$10$Ri1HiO3514.T0zUsReLM3.kcd56BfAa8d.voIKjzvshDMdIosqaYe',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-04-19 11:30:50',
                'username' => 'DG',
            ),
            4 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-01-20 12:20:45',
                'email' => 'z.benmadi@gmail.com',
                'first_name' => 'Zakarya',
                'id' => 17,
                'last_name' => 'Benmadi',
                'must_change_password' => 0,
                'password' => '$2y$10$qk.KV7h9QUz2amQwINC8COwih94uTHoZAOmDD5JaQwgAsWXtPzd2e',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-04-11 21:51:59',
                'username' => 'z.benmadi',
            ),
            5 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-02-14 17:41:07',
                'email' => 'moh.touahri@bna.dz',
                'first_name' => 'Mohamed',
                'id' => 19,
                'last_name' => 'Touahri',
                'must_change_password' => 0,
                'password' => '$2y$10$uDCEBZsvfdYOMb7J0gY1kej5ndbFtyOnjZT3UbFNgdQ7GpTo3C8FO',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-26 17:29:01',
                'username' => 'm.touahri',
            ),
            6 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-02-17 23:51:49',
                'email' => 'ig@bna.dz',
                'first_name' => NULL,
                'id' => 20,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$7qZ6K4vKcWOb3HEnfdQwpuywthKjY9eFg/bPNQ92J2dyZ3UBVDIe.',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-02-18 13:40:16',
                'username' => 'IG',
            ),
            7 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-02-19 20:53:19',
                'email' => 'mumuste.mend@gmail.com',
                'first_name' => 'Mustapha',
                'id' => 23,
                'last_name' => 'Mendil',
                'must_change_password' => 0,
                'password' => '$2y$10$jfcjYfSXNI6CgQFg6YSVWujNVfRFKDRV4m/b0OkZn1iPh0qzgBHbG',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-02-19 20:53:19',
                'username' => 'm.mustapha',
            ),
            8 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-02-23 10:58:19',
                'email' => 'der@gmail.com',
                'first_name' => NULL,
                'id' => 25,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$9DrMeUp4pZKR9Yd3pdKaWOH7WnHgo5dW53HNpOW7gz98t9gNZyktC',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 19:36:34',
                'username' => 'DER',
            ),
            9 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-03-29 14:15:19',
                'email' => 'h.belloundja@bna.dz',
                'first_name' => 'Hassiba',
                'id' => 26,
                'last_name' => 'Belloundja',
                'must_change_password' => 0,
                'password' => '$2y$10$ye6y9bodu0ejV00lH3XXC.82vvRjbzDbWBILHhGZlrFs3r9pbvada',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-28 09:05:56',
                'username' => 'h.belloundja',
            ),
            10 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-03-29 14:16:09',
                'email' => 'a.adjaoud@bna.dz',
                'first_name' => 'Abdelhadi',
                'id' => 27,
                'last_name' => 'Adjaoud',
                'must_change_password' => 0,
                'password' => '$2y$10$xOEQtZ6YIVmh565E7TQqwOgs0CrcDw.ln8qqIVrUw6jzB4Jf9JKOu',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-04-12 07:29:49',
                'username' => 'a.adjaoud',
            ),
            11 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-04-12 02:39:35',
                'email' => 'DRE187controle@bna.dz',
                'first_name' => 'Malika',
                'id' => 38,
                'last_name' => 'Maldji',
                'must_change_password' => 0,
                'password' => '$2y$10$n7UYf.0YzoWL.l.iq5SZGuyfgoXoIuZSj0Kh51PMMiHuaU3ML8LLO',
                'phone' => '0540602924',
                'remember_token' => NULL,
                'updated_at' => '2023-04-12 09:09:17',
                'username' => '747',
            ),
            12 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-04-12 02:40:58',
                'email' => 's.djellali@bna.dz',
                'first_name' => 'Djellali',
                'id' => 39,
                'last_name' => 'Siham',
                'must_change_password' => 0,
                'password' => '$2y$10$npj07Hc.dDGCuUKqaJKJ1uo1jEPhdI.ildv.Y8saOsLhGYQQ7j8ym',
                'phone' => '0555531013',
                'remember_token' => NULL,
                'updated_at' => '2023-04-12 11:32:40',
                'username' => '6969',
            ),
            13 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-04-12 07:17:32',
                'email' => 's.merghit@bna.dz',
                'first_name' => 'Soumia',
                'id' => 40,
                'last_name' => 'Merghit',
                'must_change_password' => 0,
                'password' => '$2y$10$rbnm2CFxYJfFJqHOsUOzhOeJHtpfdjvZfo5keS7vbdeb9/f5wJuiy',
                'phone' => '0696641162',
                'remember_token' => NULL,
                'updated_at' => '2023-04-17 09:46:45',
                'username' => '362',
            ),
            14 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-04-12 07:18:23',
                'email' => 'f.kheyar@bna.dz',
                'first_name' => 'Farid',
                'id' => 41,
                'last_name' => 'Kheyar',
                'must_change_password' => 0,
                'password' => '$2y$10$WTIWBPb.MiXaOVkdrH/nV.AuzAdvUaiNoAXschVM5Ziaiu0EEms6y',
                'phone' => '0550261370',
                'remember_token' => NULL,
                'updated_at' => '2023-04-17 09:46:16',
                'username' => '13057',
            ),
            15 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-13 14:12:16',
                'email' => 'cdc-garidi@bna.dz',
                'first_name' => NULL,
                'id' => 44,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$fPl91CAXEiHKsQ2yqLBOr.HqfsduZOGbcT0Bd9U090nE3TuvwJq/m',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-13 14:25:53',
                'username' => 'cdc-garidi',
            ),
            16 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-13 14:12:43',
                'email' => 'ci-garidi@bna.dz',
                'first_name' => NULL,
                'id' => 45,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$ft64i5vH4/O6tYWLIX5ql.9zgifw..ter4oTDP/h3l1.rpczTlHgC',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-13 14:51:01',
                'username' => 'ci-garidi',
            ),
            17 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-13 14:25:09',
                'email' => 'da-633@bna.dz',
                'first_name' => NULL,
                'id' => 46,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$Tp8GhYS6VEeQiES9Ba7BK.JLYMd5lb0v0kYOQJaYU/xdRHijlE/v.',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-13 14:25:09',
                'username' => 'da-633',
            ),
            18 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-16 17:59:08',
                'email' => 'cdcr@dev.dz',
                'first_name' => NULL,
                'id' => 47,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$ZnRklmOYXC1jUAGwL6GWRuP2VlSFMt7dO2vRbb3Po3tBv104gT7yG',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-16 18:51:53',
                'username' => 'cdcr',
            ),
            19 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-16 19:03:33',
                'email' => 'dre-garidi@dev.dz',
                'first_name' => NULL,
                'id' => 48,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$I4ZKiOqpVG8cUy8cyWPIiunIJBk5Qo2cWzaYz8yrFgCLKSkciviDG',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 21:45:27',
                'username' => 'dre-garidi',
            ),
            20 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 19:57:57',
                'email' => 'dre-bouzareah@bna.dz',
                'first_name' => NULL,
                'id' => 49,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$UIIeoa2ZS7wE90OhONLXw.dPTIT5InfPKO/SVUap83f3hdgDLXDNy',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 19:57:57',
                'username' => 'dre-bouzareah',
            ),
            21 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 19:58:38',
                'email' => 'DRE-EL-BIAR@bna.dz',
                'first_name' => NULL,
                'id' => 50,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$Di5m8fcm1L25FUfyNoXbA.b9Z9nuyGNPhlP2FoXhffpFyqurndr6e',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 19:58:38',
                'username' => 'DRE-EL-BIAR',
            ),
            22 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 20:01:54',
                'email' => 'DRE-KOLEA@bna.dz',
                'first_name' => NULL,
                'id' => 51,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$b66J6JOAfOI94YNNGwAsEunyJ0tm69UDiEklcu5ARBWcCHa6NjGC.',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 20:01:54',
                'username' => 'DRE-KOLEA',
            ),
            23 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 20:42:17',
                'email' => 'CDC-BOUZAREAH@bna.dz',
                'first_name' => NULL,
                'id' => 52,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$zdrVG9KnVeKNMFCQW1R6VOSPXyuT2npcS8ezXM1ee0ahLdPY42ima',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 20:42:17',
                'username' => 'CDC-BOUZAREAH',
            ),
            24 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 20:43:53',
                'email' => 'CDC-EL-BIAR@bna.dz',
                'first_name' => NULL,
                'id' => 53,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$6RYCt.bEJJD5rIKHBHxm9uRAatkgAPc62P43yf0RZInZKMTpn9cI.',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 20:43:53',
                'username' => 'CDC-EL-BIAR',
            ),
            25 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 20:44:33',
                'email' => 'CDC-KOLEA@bna.dz',
                'first_name' => NULL,
                'id' => 54,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$uOlHN3LEad0tDC4qtYrNwO7VwI0zPPKlUUx877rwwPNCXXz5t6jM.',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 20:44:33',
                'username' => 'CDC-KOLEA',
            ),
            26 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 20:46:09',
                'email' => 'CI-BOUZAREAH@bna.dz',
                'first_name' => NULL,
                'id' => 55,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$W1gQI.VcLBxbziR2QH7Ruufz.a/OWOMASbIByIjXmw/IbuNtI75iK',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 20:46:09',
                'username' => 'CI-BOUZAREAH',
            ),
            27 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 20:46:49',
                'email' => 'CI-EL-BIAR@bna.dz',
                'first_name' => NULL,
                'id' => 56,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$zZmDSGJ3IyHFq4KEzncKG.fDuxe46aYKh3Z9Y6eqHdaFm7.ukqt9K',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 20:46:49',
                'username' => 'CI-EL-BIAR',
            ),
            28 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 20:47:19',
                'email' => 'CI-KOLEA@bna.dz',
                'first_name' => NULL,
                'id' => 57,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$rP/0q9vQRAHiA5RUbSs/m.EbHZM4e7eFea6KTvDlwoeD2.egknsAO',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 20:47:19',
                'username' => 'CI-KOLEA',
            ),
            29 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 21:23:08',
                'email' => 'da-614@bna.dz',
                'first_name' => NULL,
                'id' => 58,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$XJ6Vg9yfzM8B1csICbXqL.XCZUb7zDptQkKxrM4xbcZAj1GplgVlq',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 21:23:08',
                'username' => 'da-614',
            ),
            30 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 21:23:36',
                'email' => 'da-617@bna.dz',
                'first_name' => NULL,
                'id' => 59,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$qkcV79sEJPHIFDX/drsQ5uW72AXdm4FY9dScU5n01R1K8ZDyGXEhq',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 21:23:36',
                'username' => 'da-617',
            ),
            31 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 21:24:11',
                'email' => 'da-622@bna.dz',
                'first_name' => NULL,
                'id' => 60,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$MIe64ArVIgaJ9VFtZ2375eRStSnPwVOgXfVe8d2PO9gk0OLJxuhRC',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 21:24:11',
                'username' => 'da-622',
            ),
            32 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 21:24:36',
                'email' => 'da-610@bna.dz',
                'first_name' => NULL,
                'id' => 61,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$p9Ai/vQuePggxs/Uw9Mw.erpOHqdlFzoFOpeoeJUfHITGBA0a2GSO',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 21:24:36',
                'username' => 'da-610',
            ),
            33 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 21:25:07',
                'email' => 'da-607@bna.dz',
                'first_name' => NULL,
                'id' => 62,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$Fig1TTnJ4/bTEJVeipmLPOc3SDWpMOckPf5VvYSJLbX8MIMcRiimW',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 21:25:07',
                'username' => 'da-607',
            ),
            34 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 21:25:31',
                'email' => 'da-615@bna.dz',
                'first_name' => NULL,
                'id' => 63,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$0i1ZcmXvJQWL/jxeqgQuQ.jxFzj5/jnwlvvQUVCs/6Nu7RNxmUcXe',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 21:25:31',
                'username' => 'da-615',
            ),
            35 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 21:26:15',
                'email' => 'da-605@bna.dz',
                'first_name' => NULL,
                'id' => 64,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$H2V315Ro9Kg49GPpJY5ws.UVNXTNCi/QDTbLjCi4miv1rTGsd.Aky',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 21:26:15',
                'username' => 'da-605',
            ),
            36 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 21:26:39',
                'email' => 'da-628@bna.dz',
                'first_name' => NULL,
                'id' => 65,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$uf9M2eD2DGP9zDtIXX0YoOJ.xrRmU2GjTsuiOOfy4EgL.J8TOnRHe',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 21:26:39',
                'username' => 'da-628',
            ),
            37 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 21:27:29',
                'email' => 'da-629@bna.dz',
                'first_name' => NULL,
                'id' => 66,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$0410TwTY4bT7DmNfbgPFk.ugBGy8eLvOOztAu1QZ1BztQdPf0OvLi',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 21:27:29',
                'username' => 'da-629',
            ),
            38 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-05-27 21:48:45',
                'email' => 'SG@bna.dz',
                'first_name' => NULL,
                'id' => 67,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$QY6Pg1Xr0nwsYxTnambGYOtNptR0g6Uw4qEOXJ/XchXzl06XXfKC2',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-05-27 21:48:45',
                'username' => 'SG',
            ),
            39 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-06-01 11:14:05',
                'email' => 'dre-annaba@bna.dz',
                'first_name' => NULL,
                'id' => 68,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$DQPCRDJ082em8pTOSl00KeILTVGBN9.h0jgW2HLzBpOOeuuB7RMBe',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-06-01 11:14:05',
                'username' => 'dre-annaba',
            ),
            40 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-06-01 11:14:42',
                'email' => 'da-810@bna.dz',
                'first_name' => NULL,
                'id' => 69,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$22vIv6A4.M7jy//srtHtq.o35bYiMbT5Guc4G6RqZ9frCTqKHxPbW',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-06-01 11:14:42',
                'username' => 'da-810',
            ),
            41 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-06-01 11:15:16',
                'email' => 'cdc-annaba@bna.dz',
                'first_name' => NULL,
                'id' => 70,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$8F9lPmyngfGAmQsOmOzUaOHT3tUvdc00Veo6yjiHz7ipyfeXGkgGW',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-06-01 11:15:16',
                'username' => 'cdc-annaba',
            ),
            42 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-06-01 11:15:43',
                'email' => 'ci-annaba@bna.dz',
                'first_name' => NULL,
                'id' => 71,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$btxN0/59xjkr1a7pLrjgcuUgep6bVClP/Q6X6qYxA16y4HUlpYUv2',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-06-01 11:15:43',
                'username' => 'ci-annaba',
            ),
            43 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-06-03 23:34:44',
                'email' => 'dre-constantine@bna.dz',
                'first_name' => NULL,
                'id' => 72,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$3uSBhN8scLQYmAvlg2IxYOQoX4wgiiV.L5UmBxdIWZXzOiPnDTC8O',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-06-03 23:34:44',
                'username' => 'dre-constantine',
            ),
            44 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-06-03 23:35:13',
                'email' => 'da-845@bna.dz',
                'first_name' => NULL,
                'id' => 73,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$XoMTB268SMZaTxvRLAae5.Bt63KOvqmxChxnATfsAUJEpxvaJH1ou',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-06-03 23:35:13',
                'username' => 'da-845',
            ),
            45 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-06-03 23:35:44',
                'email' => 'cdc-constantine@bna.dz',
                'first_name' => NULL,
                'id' => 74,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$8hYyutjN/d.nuAogWksy6uxa6iOpB7jwyEvAwV1bKshcka7hMrMay',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-06-03 23:35:44',
                'username' => 'cdc-constantine',
            ),
            46 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-06-03 23:36:09',
                'email' => 'ci-constantine@bna.dz',
                'first_name' => NULL,
                'id' => 75,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$xJTxPsnh7vID.h6GIU5a2uNXfdXYerPq26FpDtQgrfm4Mph4L74UW',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-06-03 23:36:09',
                'username' => 'ci-constantine',
            ),
            47 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-06-04 09:00:48',
                'email' => 'dre-setif@bna.dz',
                'first_name' => NULL,
                'id' => 76,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$5WEBEf3Vjmn80J8EJRGMA.t6B.XaFV.EK9z1mYn0NWqxr4w3EPBbC',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-06-04 09:00:48',
                'username' => 'dre-setif',
            ),
            48 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-06-04 09:01:11',
                'email' => 'cdc-setif@bna.dz',
                'first_name' => NULL,
                'id' => 77,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$pMBKERYjyNAPOcZLEtf8zeSxPnJ7sIK469rVFDh5LWf5mgcneKhS.',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-06-04 09:01:11',
                'username' => 'cdc-setif',
            ),
            49 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-06-04 09:01:32',
                'email' => 'ci-setif@bna.dz',
                'first_name' => NULL,
                'id' => 78,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$reRVZQpVC4xqmBQImOWzMuRbUphVjMbZjMitV5NizKvjdIyGXrCVy',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-06-04 09:01:32',
                'username' => 'ci-setif',
            ),
            50 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-06-04 09:02:25',
                'email' => 'da-704@bna.dz',
                'first_name' => NULL,
                'id' => 79,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$kVNzBYX0LICNdSYIq1oySOFuS2iPVaWyuzjxz/gS2WwBtABksa/vm',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-06-04 09:02:25',
                'username' => 'da-704',
            ),
            51 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-07-09 09:54:05',
                'email' => 'dre-oran@bna.dz',
                'first_name' => NULL,
                'id' => 80,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$PVttjlt.3GALo2luve3tauRCcfRIkDORmlHeR3.MUBrXl9pxdAxHW',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-07-09 09:54:05',
                'username' => 'dre-oran',
            ),
            52 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-07-09 09:55:13',
                'email' => 'cdc-oran@bna.dz',
                'first_name' => NULL,
                'id' => 81,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$Nd.aTsjZxmfSiZbDzBkogePlf8Bso60xqXVFpNc.VLSCa9Urmjioe',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-07-09 09:55:13',
                'username' => 'cdc-oran',
            ),
            53 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-07-09 09:55:58',
                'email' => 'ci-oran@bna.dz',
                'first_name' => NULL,
                'id' => 82,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$iiOy4sOvrfm33qm4a3a99.9eesBlbJh02dRSYsUhn8oUZAbG1r6Tq',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-07-09 09:55:58',
                'username' => 'ci-oran',
            ),
            54 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-07-09 09:56:42',
                'email' => 'da-951@bna.dz',
                'first_name' => NULL,
                'id' => 83,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$x7Rp28zXSAXXrlODuAcqM.Im2Z9fAyRCVi1u/vt3V0S8b2ixXOFwS',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-07-09 09:56:42',
                'username' => 'da-951',
            ),
            55 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-07-12 19:11:38',
                'email' => 'DRE-TIZIOUZOU@bna.dz',
                'first_name' => NULL,
                'id' => 84,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$AyRDxQObTV4xVMFv6h7Rruc3HdSbfiAU1foijnGDLIraf8x7TaiCG',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-07-12 19:11:38',
                'username' => 'DRE-TIZIOUZOU',
            ),
            56 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-07-12 19:12:08',
                'email' => 'CDC-TIZIOUZOU@bna.dz',
                'first_name' => NULL,
                'id' => 85,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$peNk.xw1V1Akpc0bbnzkl.D.Z2RRl/kxW/eOhcVtNK/ERgFVWQJv6',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-07-12 19:12:08',
                'username' => 'CDC-TIZIOUZOU',
            ),
            57 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-07-12 19:12:32',
                'email' => 'CI-TIZIOUZOU@bna.dz',
                'first_name' => NULL,
                'id' => 86,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$w2l5oCobM3vLlAuJCW1BSuUC2x6jG4hIv7ijEFYJMEh9vkKR2elOi',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-07-12 19:12:32',
                'username' => 'CI-TIZIOUZOU',
            ),
            58 => 
            array (
                'avatar' => NULL,
                'created_at' => '2023-07-12 19:13:14',
                'email' => 'DA-581@bna.dz',
                'first_name' => NULL,
                'id' => 87,
                'last_name' => NULL,
                'must_change_password' => 0,
                'password' => '$2y$10$LRkWTzQkbKonn2cKciE2eOadfALuoqJaIU9HnT.0GR3VqjyJM.lke',
                'phone' => NULL,
                'remember_token' => NULL,
                'updated_at' => '2023-07-12 19:13:14',
                'username' => 'DA-581',
            ),
        ));
        
        
    }
}